version: '3.8'

services:
  core-service:
    build: .
    container_name: efms-core-service
    ports:
      - "8082:8082"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-prod}
      - DB_URL=${DB_URL}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
      - JWT_SECRET=${JWT_SECRET}
      - JWT_EXPIRATION_MS=${JWT_EXPIRATION_MS:-86400000}
      - PRIVATE_IDENTITY_SERVICE_URL=${PRIVATE_IDENTITY_SERVICE_URL:-http://172.31.31.253:8081}
    # depends_on:
    #   - core-db


volumes:
  core-db-data:
